// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// p2pDistance
NumericMatrix p2pDistance(NumericMatrix dataFrom, NumericMatrix dataTo, bool greatCircle);
RcppExport SEXP ruisu_p2pDistance(SEXP dataFromSEXP, SEXP dataToSEXP, SEXP greatCircleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataFrom(dataFromSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataTo(dataToSEXP);
    Rcpp::traits::input_parameter< bool >::type greatCircle(greatCircleSEXP);
    rcpp_result_gen = Rcpp::wrap(p2pDistance(dataFrom, dataTo, greatCircle));
    return rcpp_result_gen;
END_RCPP
}
