// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP ruisu_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
// p2pDistance
NumericMatrix p2pDistance(NumericMatrix dataFrom, NumericMatrix dataTo);
RcppExport SEXP ruisu_p2pDistance(SEXP dataFromSEXP, SEXP dataToSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataFrom(dataFromSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataTo(dataToSEXP);
    __result = Rcpp::wrap(p2pDistance(dataFrom, dataTo));
    return __result;
END_RCPP
}
