// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// p2pDistance
NumericMatrix p2pDistance(NumericMatrix dataFrom, NumericMatrix dataTo, int greatCircle);
RcppExport SEXP ruisu_p2pDistance(SEXP dataFromSEXP, SEXP dataToSEXP, SEXP greatCircleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataFrom(dataFromSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dataTo(dataToSEXP);
    Rcpp::traits::input_parameter< int >::type greatCircle(greatCircleSEXP);
    __result = Rcpp::wrap(p2pDistance(dataFrom, dataTo, greatCircle));
    return __result;
END_RCPP
}
