#' @title Generate concentric buffer rings around the Peruvian coastline
#'
#' @description
#' Creates a set of non-overlapping concentric buffer rings from the
#' Peruvian coastline using the QGIS algorithm
#' \code{native:multiringconstantbuffer}. Each ring has a constant width
#' defined by \code{distance}, and the total number of rings is specified
#' by \code{n_rings}.
#'
#' @param distance Numeric. Width of each buffer ring. Units are determined
#'   by the coordinate reference system of the input layer and the value of
#'   \code{units}.
#' @param n_rings Integer. Number of concentric rings to generate.
#' @param units Character string indicating the distance units. Currently
#'   accepted values are \code{"nm"} (nautical miles), \code{"km"}
#'   (kilometres), and \code{"m"} (metres).
#'
#' @return An object of class \code{sf} containing the generated buffer
#'   rings as polygon geometries. The output includes the attributes
#'   generated by the QGIS algorithm, such as ring identifiers and
#'   distances.
#'
#' @details
#' The function is a wrapper around the QGIS
#' \code{native:multiringconstantbuffer} algorithm accessed through
#' the \pkg{qgisprocess} package.
#'
#' Rings are generated as consecutive, non-overlapping distance bands:
#' for example, a distance of 10 and \code{n_rings = 4} produces the
#' intervals \eqn{[0,10]}, \eqn{(10,20]}, \eqn{(20,30]}, and
#' \eqn{(30,40]}.
#'
#' @export
#'
#' @seealso
#' \code{\link[qgisprocess:qgis_run_algorithm]{qgis_run_algorithm}}
#'
#' @examples
#' multiringconstantbuffer(distance = 40, n_rings = 5)
multiring_constant_buffer <- \(distance, n_rings, units = "nm"){
  qgis_run_algorithm(
    algorithm = "native:multiringconstantbuffer",
    INPUT = perCoastline,
    RINGS = n_rings,
    DISTANCE = distance/(1.852*60),
    DISSOLVE = TRUE
  ) |>

    qgis_extract_output() |>

    st_read()
}
