# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

p2pDistance <- function(dataFrom, dataTo, greatCircle = 0L) {
    .Call('ruisu_p2pDistance', PACKAGE = 'ruisu', dataFrom, dataTo, greatCircle)
}

