# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('ruisu_rcpp_hello', PACKAGE = 'ruisu')
}

p2pDistance <- function(dataFrom, dataTo) {
    .Call('ruisu_p2pDistance', PACKAGE = 'ruisu', dataFrom, dataTo)
}

