# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Función para obtener distancia entre dos puntos.
#' @param dataFrom \code{data.frame} with lon-lat values.
#' @param dataTo Reference lon-lat \code{data.frame}.
#' @param greatCircle \code{logical}; si es \code{FALSE}, se devolverá la distancia euclidiana: si es
#' \code{TRUE} devolverá la DIstancia de Gran Círculo (WGS84).
#' @useDynLib ruisu
#' @export
#' @importFrom Rcpp evalCpp
p2pDistance <- function(dataFrom, dataTo, greatCircle = FALSE) {
    .Call('ruisu_p2pDistance', PACKAGE = 'ruisu', dataFrom, dataTo, greatCircle)
}

